[package]
name = "rust_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
bytes = { version = "1.11.1", features = ["serde"] }
rand = "0.10.0"
rustls = { version = "0.23", default-features = false, features = ["logging", "std", "ring"] }
tokio-rustls = { version = "0.26.4", default-features = false, features = ["logging", "ring"] }
rustls-pemfile = "2.2.0"
uuid = { version = "1.19.0", features = ["v4"] }
socket2 = "0.6.2"
moka = { version = "0.12.13", features = ["future"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tracing-appender = "0.2.4"
chrono = "0.4.43"
flate2 = "1.1.9"
hmac = "0.12.1"
sha2 = "0.10.9"
serde_json = "1.0.149"
dashmap = { version = "6.1.0", features = ["serde"] }
toml = "1.0.0"
thiserror = "2.0.18"
axum = "0.8.8"
http = "1.4.0"
redb = "3.1.0"
hex = "0.4.3"
governor = "0.10.4"
sysinfo = "0.38.1"

[profile.release]
strip = true      # 强制剔除符号（缩小 GNU 体积的关键）
lto = true        # 开启全程序优化
opt-level = "z"   # 针对体积优化